import { ArrowDown, ArrowRight, BarChart3, Boxes, Braces, BriefcaseBusiness, Code2, Database, Download, ExternalLink, Gauge, GitBranch, Layers3, Mail, Sparkles, TerminalSquare, Workflow } from "lucide-react";
import { SharePortfolio } from "@/components/share-portfolio";
import { ProfileMap } from "@/components/profile-map";

const profile = { email: "fadywafaa36@gmail.com", github: "https://github.com/fady-wafaa", linkedin: "https://www.linkedin.com/in/fady-wafa/", resume: "/Fady_Wafa_Resume.pdf" };
const nav = [["SuiteFleet", "#suitefleet"], ["Architecture", "#architecture"], ["Performance", "#performance"], ["Experience", "#experience"], ["Stack", "#stack"], ["Contact", "#contact"]] as const;
const metrics = [
  { value: "4+ Years", label: "Frontend experience", note: "Building & modernizing production SaaS" },
  { value: "1M+ / Day", label: "Platform requests", note: "SuiteFleet infrastructure scale" },
  { value: "+20%", label: "Performance uplift", note: "Lighthouse-driven application improvement" },
  { value: "React 16 → 19", label: "Modernization", note: "Staged React & TypeScript adoption" },
];
const stack = [
  { icon: Code2, title: "Frontend Core", items: ["React.js", "React 19", "Next.js", "TypeScript", "JavaScript ES6+", "HTML5 / CSS3"] },
  { icon: Sparkles, title: "UI & Styling", items: ["Tailwind CSS", "shadcn/ui", "Material UI", "Bootstrap", "GSAP", "Three.js"] },
  { icon: Database, title: "State & Data Layer", items: ["TanStack Query", "Zustand", "Redux Toolkit", "REST APIs", "OpenAPI Integration"] },
  { icon: BarChart3, title: "Data-Heavy UI", items: ["AG Grid", "Server-Side Loading", "Filtering", "Sorting", "Bulk Operations", "Data Export"] },
  { icon: Gauge, title: "Performance", items: ["Lighthouse", "Core Web Vitals", "Code Splitting", "Lazy Loading", "Caching", "CDN"] },
  { icon: Workflow, title: "Architecture & Practices", items: ["Feature-Based Architecture", "Modular Design", "Reusable Components", "Accessibility / WCAG", "RBAC", "Code Reviews"] },
];

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <header className="section-heading"><p className="eyebrow"><span />{eyebrow}</p><h2>{title}</h2>{copy ? <p className="section-copy">{copy}</p> : null}</header>;
}

export default function Home() {
  return <main>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <nav className="nav-shell" aria-label="Primary navigation"><div className="nav-inner">
      <a className="brand" href="#top" aria-label="Fady Wafa Nagy, home"><span className="brand-mark">F</span><span><strong>FADY WAFA NAGY</strong><small>FRONTEND SOFTWARE ENGINEER</small></span></a>
      <div className="nav-links">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div>
      <div className="nav-actions"><a className="button button-ghost small" href={profile.resume} download><Download size={15} /> CV</a><SharePortfolio compact /></div>
      <details className="mobile-menu"><summary aria-label="Open navigation"><span /><span /><span /></summary><div>{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}<a href={profile.resume} download>Download CV</a></div></details>
    </div></nav>

    <div id="main-content">
      <section id="top" className="hero section-grid"><div className="hero-glow" aria-hidden="true" /><div className="container hero-layout">
        <div className="hero-copy"><p className="eyebrow"><span />React · Next.js · TypeScript · SaaS Architecture</p><p className="hero-name">FADY WAFA NAGY</p><div className="role-pill">Frontend Software Engineer</div><h1>Building scalable, high-performance SaaS interfaces with React, Next.js &amp; TypeScript.</h1><p className="hero-lede">Frontend engineer with 4+ years of experience building and modernizing production SaaS applications, focused on frontend architecture, performance, data-heavy interfaces and scalable React systems.</p><div className="hero-actions"><a className="button button-primary" href="#suitefleet">Explore SuiteFleet Case Study <ArrowDown size={16} /></a><a className="button button-ghost" href={profile.resume} download><Download size={16} /> Download Resume</a><a className="icon-button" href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><GitBranch size={18} /></a><a className="icon-button" href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><BriefcaseBusiness size={18} /></a></div></div>
        <aside className="system-card" aria-label="Architecture and scale profile"><div className="system-card-head"><span><TerminalSquare size={15} /> Architecture &amp; Scale Profile</span><small>PRODUCTION FOCUS</small></div>{[
          ["React 16 → React 19 modernization", "Staged migration across a large production frontend", "MODERNIZED"],
          ["Typed frontend contracts", "TypeScript adoption for safer business logic and API integration", "TYPED"],
          ["Feature-based architecture", "Clear domain boundaries and reusable UI foundations", "MODULAR"],
          ["+20% performance uplift", "Code splitting, caching and rendering optimization", "MEASURED"],
          ["Data-heavy React interfaces", "AG Grid, server-side loading and responsive operations", "SCALED"],
        ].map(([title, text, status], index) => <div className="system-row" key={title}><span className="system-index">0{index + 1}</span><span><strong>{title}</strong><small>{text}</small></span><em>{status}</em></div>)}<div className="system-foot"><span><i /> Production experience</span><strong>1M+ platform requests / day</strong></div></aside>
      </div></section>

      <section className="metrics-band" aria-label="Key career metrics"><div className="container metrics-grid">{metrics.map(metric => <article key={metric.value}><strong>{metric.value}</strong><span>{metric.label}</span><small>{metric.note}</small></article>)}</div></section>

      <section id="suitefleet" className="section section-grid"><div className="container"><div className="title-row"><SectionTitle eyebrow="Flagship case study · Azdan" title="SuiteFleet — Scaling a Multi-Tenant Logistics Frontend" copy="A production B2B logistics platform supporting end-to-end fleet and delivery operations." /><a className="status-chip" href="https://www.suitefleet.com/" target="_blank" rel="noreferrer"><i /> Product website <ExternalLink size={13} /></a></div>
        <div className="case-grid">
          <article className="case-card"><span className="card-number">01 / CONTEXT</span><Boxes size={23} /><h3>Enterprise Logistics Platform</h3><p>Task management, route planning, driver operations, analytics, reporting, RBAC and multi-tenant workflows across fleet operations.</p><div className="tag-row"><span>Fleet Ops</span><span>Task Workflows</span><span>Multi-Tenant</span></div></article>
          <article className="case-card"><span className="card-number">02 / CHALLENGE</span><Layers3 size={23} /><h3>Data-Heavy UI &amp; State Load</h3><p>Complex filters, grids and operational panels needed smooth state updates while preserving tenant configuration and English/Arabic direction.</p><div className="tag-row"><span>Rendering</span><span>State</span><span>RTL</span></div></article>
          <article className="case-card"><span className="card-number">03 / CONTRIBUTION</span><Braces size={23} /><h3>Modernization &amp; Architecture</h3><p>Modernized React, adopted TypeScript, established reusable feature boundaries and integrated typed REST APIs with role-based access control.</p><div className="tag-row"><span>React 19</span><span>TypeScript</span><span>RBAC</span></div></article>
          <article className="case-card"><span className="card-number">04 / SYSTEMS</span><BarChart3 size={23} /><h3>Feature Boundaries &amp; AG Grid</h3><p>Reduced unnecessary renders, improved list and grid strategies and created reusable UI and form abstractions for faster feature delivery.</p><div className="tag-row"><span>AG Grid</span><span>Reusable UI</span><span>Data Export</span></div></article>
          <article className="case-card case-wide"><span className="card-number">05 / VERIFIED RESULT</span><Gauge size={23} /><h3>Performance &amp; Type Safety Gains</h3><p>Achieved an approximately 20% application performance improvement through code splitting, lazy loading, bundle optimization, caching and rendering improvements—while strengthening compile-time safety across business rules and API boundaries.</p><div className="result-row"><span><strong>+20%</strong> performance improvement</span><span><strong>Typed</strong> REST integration</span><span><strong>English + Arabic</strong> RTL parity</span></div></article>
        </div>
        <div className="workbench" aria-label="Conceptual dispatch workbench visualization"><div className="workbench-top"><span><i /> Conceptual Dispatch Workbench Visualization</span><small>Representative demo data</small></div><div className="workbench-body"><div className="workbench-sidebar"><h3>OPERATIONS</h3>{["Unassigned tasks", "Active drivers", "Shift coverage", "Delivery exceptions"].map((x, i) => <div key={x}><span>{x}</span><strong>{[24, 68, 82, 7][i]}</strong><small style={{width: `${[42,76,84,24][i]}%`}} /></div>)}</div><ProfileMap /><div className="workbench-sidebar right"><h3>SHIFT STATUS</h3>{["Available", "On route", "At hub", "Offline"].map((x, i) => <div key={x}><span>{x}</span><strong>{[18,31,12,7][i]}</strong><small style={{width: `${[50,82,34,18][i]}%`}} /></div>)}</div></div><footer><span><i className="cyan" /> Driver</span><span><i className="green" /> Task cluster</span><span><i className="red" /> Exception</span><strong>Concept only · no production telemetry</strong></footer></div>
      </div></section>

      <section id="architecture" className="section section-darker section-grid"><div className="container"><SectionTitle eyebrow="System modernization" title="Architectural Evolution: Modernizing the SaaS Core" copy="A structured progression from a legacy React frontend toward a typed, modular and maintainable system." /><div className="evolution">{[
        ["01", "Legacy React 16", "Untyped flows and tightly coupled modules"], ["02", "React 19 Modernization", "Staged upgrades across the production frontend"], ["03", "TypeScript Adoption", "Safer contracts for UI, state and API integration"], ["04", "Feature-Based Structure", "Domain-aligned modules with clear boundaries"], ["05", "Reusable Foundations", "Shared components and form abstractions"], ["06", "Rendering Optimization", "Focused state, list and grid performance"],
      ].map(([n,title,copy]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="architecture-notes"><article><h3><span>—</span> Legacy constraints</h3><ul><li>Large modules increased the cost of change.</li><li>Changing API shapes were harder to trace safely.</li><li>Shared state could trigger broader rendering work.</li></ul></article><article><h3><span>+</span> Modernized practices</h3><ul><li>Typed REST contracts reveal mismatches earlier.</li><li>Feature boundaries improve independent delivery.</li><li>Reusable foundations reduce repeated implementation.</li></ul></article></div></div></section>

      <section id="performance" className="section section-grid"><div className="container"><SectionTitle eyebrow="Performance engineering" title="+20% Application Performance Improvement" copy="Targeted optimization across loading, caching, bundle delivery and data-heavy rendering." /><div className="performance-flow"><article><span>BEFORE</span><h3>Legacy frontend</h3><p>Large initial bundles, repeated work and expensive interface updates.</p></article><ArrowRight aria-hidden /><article className="performance-main"><span>OPTIMIZATION</span><h3>Code Splitting · Caching · AG Grid</h3><p>Route-aware loading, lazy boundaries, bundle optimization, improved rendering and smarter server-side data strategies.</p></article><ArrowRight aria-hidden /><article className="performance-result"><span>RESULT</span><strong>+20%</strong><h3>Performance uplift</h3></article></div><div className="performance-cards">{["Code Splitting & Lazy Loading", "Bundle Optimization", "Caching & State Optimization", "List & Grid Rendering"].map((x,i) => <article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Load features when users need them.", "Reduce unnecessary initial delivery cost.", "Avoid repeated fetch and render work.", "Keep operational tables responsive."][i]}</p></article>)}</div></div></section>

      <section id="experience" className="section section-darker section-grid"><div className="container"><SectionTitle eyebrow="Track record" title="Engineering Impact &amp; Experience" /><div className="timeline">
        <article><span className="timeline-dot" /><header><div><h3>Frontend Software Engineer</h3><p>Azdan · Dubai, Remote</p></div><time>NOV 2022 — PRESENT</time></header><p>Contributing to SuiteFleet, a high-traffic multi-tenant logistics SaaS platform, building scalable frontend systems for fleet and delivery operations.</p><ul><li>React 16 → React 19 and TypeScript modernization</li><li>+20% Lighthouse-driven application performance improvement</li><li>Feature-based architecture, RBAC, multi-tenancy and bilingual RTL</li><li>Data-heavy UI, AG Grid and typed REST API integration</li></ul></article>
        <article><span className="timeline-dot" /><header><div><h3>NetSuite Developer</h3><p>Azdan · Dubai, Remote</p></div><time>NOV 2021 — NOV 2022</time></header><p>Built NetSuite ERP customizations, workflows, forms and business logic, including React interfaces integrated with NetSuite services.</p><ul><li>SuiteScript 2.1 and operational workflow automation</li><li>Clients included Alliance Global, Deyaar, Naga, Diamond Group and Al Khaleej Training &amp; Education</li></ul></article>
        <article><span className="timeline-dot" /><header><div><h3>Freelance Frontend Developer</h3><p>Remote · Project-based</p></div><time>PROJECT-BASED</time></header><p>Developed frontend interfaces and small web applications using JavaScript and React, while mentoring learners and junior developers.</p></article>
      </div></div></section>

      <section id="stack" className="section section-grid"><div className="container"><SectionTitle eyebrow="System responsibilities" title="Technical Stack by Engineering Responsibility" copy="A practical stack organized around the work it enables—not a wall of technology logos." /><div className="stack-grid">{stack.map(({icon:Icon,title,items}) => <article key={title}><Icon size={19} /><h3>{title}</h3><div>{items.map(x => <span key={x}>{x}</span>)}</div></article>)}</div><div className="philosophy"><SectionTitle eyebrow="Principles" title="Engineering Philosophy" /><div className="philosophy-grid">{[
        ["01","Scalability Over Shortcuts","Build frontend foundations that remain maintainable as products and teams grow."], ["02","Performance Is Part of UX","Fast interfaces are not just technical achievements; they shape the product experience."], ["03","Abstractions Should Reduce Complexity","Reusable components should make delivery easier, not introduce ceremony."], ["04","Build for Production","Account for errors, changing data, permissions, accessibility and real user behavior."],
      ].map(([n,title,copy]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></div></section>

      <section id="contact" className="contact-section section-grid"><div className="container contact-card"><div><p className="eyebrow"><span />Available for frontend opportunities</p><h2>Let&apos;s build interfaces that scale effortlessly.</h2><p>Open to frontend engineering opportunities focused on scalable SaaS products, architecture and high-performance user experiences.</p><div className="availability"><span><i /> Cairo, Egypt · Remote &amp; relocation</span><span><i /> Response time: 1–2 days</span></div></div><div className="contact-actions"><a className="button button-primary" href={`mailto:${profile.email}`}><Mail size={16} /> {profile.email}</a><a className="button button-ghost" href={profile.resume} download><Download size={16} /> Download Resume</a><div><a className="button button-ghost" href={profile.linkedin} target="_blank" rel="noreferrer"><BriefcaseBusiness size={16} /> LinkedIn</a><a className="button button-ghost" href={profile.github} target="_blank" rel="noreferrer"><GitBranch size={16} /> GitHub</a></div><SharePortfolio /></div></div></section>
    </div>
    <footer className="footer"><div className="container"><div><strong>FADY WAFA NAGY</strong><span>Frontend Software Engineer · React · Next.js · TypeScript</span></div><nav aria-label="Footer navigation">{nav.map(([label,href]) => <a key={href} href={href}>{label}</a>)}</nav><small>© {new Date().getFullYear()} Fady Wafa Nagy</small></div></footer>
  </main>;
}
